CREATE ROLE ADMIN13_SESSION;
CREATE ROLE ADMIN13_ROLE_PUBLIC;
CREATE ROLE ADMIN13_ROLE_DIR_HOTEL;
CREATE ROLE ADMIN13_ROLE_DIR_FINANCIER;
CREATE ROLE ADMIN13_ROLE_GOUVERNANTE;
CREATE ROLE ADMIN13_ROLE_RECEPTIONNISTE;
CREATE ROLE ADMIN13_ROLE_CLIENT;

--Role Session
--GRANT CONNECT TO ADMIN13_SESSION;
 

--Role public
GRANT ADMIN13_SESSION TO ADMIN13_ROLE_PUBLIC;
GRANT SELECT ON ADMIN13.VCHAMBRES_LIBRES TO ADMIN13_ROLE_PUBLIC;
 

--Role client
GRANT ADMIN13_ROLE_PUBLIC TO ADMIN13_ROLE_CLIENT;
GRANT SELECT, UPDATE ON ADMIN13.CLIENTS TO ADMIN13_ROLE_CLIENT;
GRANT SELECT ON ADMIN13.RESERVATION TO ADMIN13_ROLE_CLIENT;
 

--Role dir hotel
GRANT ADMIN13_ROLE_PUBLIC TO ADMIN13_ROLE_DIR_HOTEL;
GRANT SELECT,UPDATE,INSERT ON ADMIN13.CLIENTS TO ADMIN13_ROLE_DIR_HOTEL;
GRANT SELECT,UPDATE,INSERT ON ADMIN13.RESERVATION TO ADMIN13_ROLE_DIR_HOTEL;
GRANT SELECT,UPDATE,INSERT ON ADMIN13.CHAMBRE TO ADMIN13_ROLE_DIR_HOTEL;
 

--Role dir financier
GRANT ADMIN13_ROLE_PUBLIC TO ADMIN13_ROLE_DIR_FINANCIER;
GRANT SELECT ON ADMIN13.CLIENTS TO ADMIN13_ROLE_DIR_FINANCIER;
GRANT SELECT ON ADMIN13.VRESERVATIONS_AVEC_FACT TO ADMIN13_ROLE_DIR_FINANCIER; 
 

--Role gouvernante
GRANT ADMIN13_ROLE_PUBLIC TO ADMIN13_ROLE_GOUVERNANTE;
GRANT SELECT ON ADMIN13.CHAMBRE TO ADMIN13_ROLE_GOUVERNANTE;
 

--Role réceptionniste
GRANT ADMIN13_ROLE_GOUVERNANTE TO ADMIN13_ROLE_RECEPTIONNISTE;
GRANT UPDATE ON ADMIN13.CHAMBRE TO ADMIN13_ROLE_RECEPTIONNISTE;
GRANT SELECT,UPDATE,INSERT ON ADMIN13.RESERVATION TO ADMIN13_ROLE_RECEPTIONNISTE;
GRANT SELECT,UPDATE ON ADMIN13.CLIENTS TO ADMIN13_ROLE_RECEPTIONNISTE;
 

GRANT ADMIN13_ROLE_CLIENT TO USER1, USER2, USER3;
GRANT ADMIN13_ROLE_GOUVERNANTE TO USER4;
GRANT ADMIN13_ROLE_RECEPTIONNISTE TO USER5;
GRANT ADMIN13_ROLE_DIR_FINANCIER TO USER6;
GRANT ADMIN13_ROLE_DIR_HOTEL TO USER7;

COMMIT;
