CREATE OR REPLACE VIEW VCHAMBRES_LIBRES AS SELECT * FROM CHAMBRE WHERE DISPONIBLE = 1;

CREATE OR REPLACE VIEW VRESERVATIONS_AVEC_FACT AS SELECT * FROM RESERVATION WHERE FACTURE_ID IS NOT NULL;

COMMIT;