CONNECT ADMIN13/admin@cienetdb

DROP ROLE ADMIN13_SESSION;
DROP ROLE ADMIN13_ROLE_PUBLIC;
DROP ROLE ADMIN13_ROLE_DIR_HOTEL;
DROP ROLE ADMIN13_ROLE_DIR_FINANCIER;
DROP ROLE ADMIN13_ROLE_GOUVERNANTE;
DROP ROLE ADMIN13_ROLE_RECEPTIONNISTE;
DROP ROLE ADMIN13_ROLE_CLIENT;

DROP VIEW VCHAMBRES_LIBRES;
DROP VIEW VRESERVATIONS_AVEC_FACT;

DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE CLIENTS CASCADE CONSTRAINTS;
DROP TABLE COPIECLIENTS CASCADE CONSTRAINTS;
DROP TABLE CHAMBRE CASCADE CONSTRAINTS;

COMMIT;
